<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script>
        const p = new Promise((resolve,reject)=>{
            // resolve('hello world');
            reject('have an error')
        })
        //await必须放在function里面
        async function fn(){
            try {
                let result = await p;  //await后面接的必须是promise对象
                console.log(result);
                // await返回的结果是promise对象成功返回的值
            } catch (error) {
                // 如果想要去捕获promise里的错误需要通过trycatch来捕获
                console.log(error);
            }
            
        }
        fn();
    </script>
</body>
</html>